name: aimemosnap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  dio: ^5.1.2
  flutter_animate: ^4.1.1
  google_sign_in: ^6.1.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  google_maps_flutter: ^2.2.8  
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  simple_animations: ^5.0.0+3
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  cloudinary_public: ^0.23.1
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true